#Python environment for: https://github.com/xraypy/xraylarch
#Target: *FULL* environment for Larch (Wx) + SILX (Qt) Jupyter + GL
#NOTE: first install packages in apt.txt
#Usage: conda env create -f environment.yml
name: larch
channels:
    - defaults
dependencies:
    - python == 3.7
    - pip
    - nodejs
    - wxpython >= 4.0.4
    - pip:
        - numpy >= 1.16
        - scipy >= 1.2
        - matplotlib >= 3.0
        - h5py >= 2.9
        - scikit-learn
        - scikit-image
        - sqlalchemy >= 1.3
        - pillow
        - requests
        - pandas >= 0.25
        - lmfit >= 1.0.0
        - xraydb >= 4.3
        - pyyaml
        - psutil
        - nose
        - pytest
        - termcolor
        - hdf5plugin >= 2.1
        - fabio >= 0.7
        - pyfai
        - six
        - silx >= 0.12
        - ipython >= 7.10
        - ipykernel >= 5.1
        - jupyterlab_server
        - jupyterlab >= 1.0
        - ipywidgets >= 7.5
        - notebook
        - jupyterhub
        - ipympl
        - nbsphinx
        - widgetsnbextension >= 3.5.0
        - peakutils >= 1.3
        - asteval >= 0.9.18
        - uncertainties >= 3.0
        - pyshortcuts >= 1.7
        - wxutils >= 0.2.3
        - wxmplot >= 0.9.40
        - pycifrw
        - git+https://github.com/xraypy/xraylarch.git

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)