#Python environment for running Larch Jupyter examples on mybinder.org
#Usage: automatically built
name: larch-binder
channels:
    - defaults
dependencies:
    - python=3.7
    - pip
    - nodejs
    - pyqt=5
    - wxpython>=4.0.3
    - numpy>=1.16
    - scipy>=1.2
    - matplotlib>=3.0
    - h5py>=2.9
    - pandas
    - scikit-image
    - scikit-learn
    - requests
    - sqlalchemy>=0.9
    - conda-forge::xraylib
    - conda-forge::lmfit>=0.9.13
    - GSECARS::xraylarch>=0.9.46
    - pip:
        #: utils
        - xraydb
        - hdf5plugin
        - termcolor
        - pyyaml
        - palettable
       #: Jupyter
        - jupyterlab_server
        - jupyterlab>=1.0
        - ipywidgets>=7.5
        - jupyterhub
        - ipympl
        - widgetsnbextension>=3.5.0