#Python environment for: https://github.com/xraypy/xraylarch
#Target: *FULL* environment for Larch (Wx) + SILX (Qt) Jupyter + GL
#NOTE: first install packages in apt.txt
#Usage: conda env create -f environment.yml
name: larch
channels:
    - defaults
dependencies:
    - python == 3.7
    - pip
    - nodejs
    - GSECARS::xraylarch >= 0.9.46
    - pip:
        - ipython >= 7.10
        - ipykernel >= 5.1
        - jupyterlab_server
        - jupyterlab >= 1.0
        - ipywidgets >= 7.5
        - notebook
        - jupyterhub
        - ipympl
        - nbsphinx
        - widgetsnbextension >= 3.5.0

#: -> run 'postBuild' script to complete install of Jupyter extensions (NOTE: automatically run on binderhub)